### ISSUE TITLE
Document Home changed and old links don't redirect properly

### ISSUE THREAD

**Issue by co60ca** [AdobeDocs/campaign-classic.en#29]
Hi there,

It seems like Adobe changed the way their docs are hosted

Old:
https://docs.adobe.com/content/help/en/campaign-classic/using/configuring-campaign-classic/schema-reference/elements-and-attributes.html
New:
https://experienceleague.adobe.com/docs/campaign-classic/using/configuring-campaign-classic/schema-reference/elements-and-attributes.html

If you go to the old link the redirect goes to https://experienceleague.adobe.com/#dashboard/profile instead

Why not just set the redirect to use a permanent redirect (301) and use the pattern to set the redirect? This kills your Google links and any bookmarks that people may have.

**Comment by BertrandSAdobe** [comment]
Hi @co60ca,

This was during the migration process. It should work now. Please confirm.

Thanks

**Comment by co60ca** [comment]
The old link which is from my bookmarks still doesn't work as expected.

https://docs.adobe.com/content/help/en/campaign-classic/using/configuring-campaign-classic/schema-reference/elements-and-attributes.html

**Comment by BertrandSAdobe** [comment]
Strange, this is working fine yet.
I'm directly redirected to https://experienceleague.adobe.com/docs/campaign-classic/using/configuring-campaign-classic/schema-reference/elements-and-attributes.html?lang=en#configuring-campaign-classic

**Comment by co60ca** [comment]
Ahhh, caching in my browser perhaps. My bad.

**Comment by co60ca** [comment]
Yup, verified: caching. Clear your cache and it works. Not sure why the cached redirect stayed so long.
